version: '3.8'

services:
  headartworks-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - SESSION_SECRET=dev-session-secret-123
      - PUBLIC_STOREFRONT_API_TOKEN=demo-token
      - PRIVATE_STOREFRONT_API_TOKEN=demo-private-token
      - PUBLIC_STORE_DOMAIN=demo-store.myshopify.com
      - PUBLIC_STOREFRONT_ID=demo-storefront-id
    volumes:
      # Mount source code for live reload during development
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    stdin_open: true
    tty: true
